#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  COUCHDB_NAME:
    container_name: COUCHDB_NAME
    image: hyperledger/fabric-couchdb:latest
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "COUCHDB_PORT:5984"

  PEER_NAME:
    container_name: PEER_NAME
    extends:
      file:  base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=PEER_NAME
      - CORE_PEER_LOCALMSPID=MSP_ID
      - CORE_PEER_ADDRESS=PEER_NAME:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=COUCHDB_NAME:5984
    ports:
      - PEER_LISTEN_PORT:7051
      - PEER_EVENT_PORT:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/ORG_NAME.example.com/peers/PEER_NAME/:/etc/hyperledger/crypto/peer
        - ../mount/PEER_NAME/var/hyperledger/production:/var/hyperledger/production
    depends_on:
        - COUCHDB_NAME
